version: "2.3"
services:
  kaggle:
    build: docker/
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONPATH=/home/working/src
    env_file:
      - ./.env
    container_name: kaggle
    volumes:
      - $PWD:/home/working
    working_dir: /home/working
    ports:
      - 8899:8899  # jupyter
      - 8501:8501  # streamlit
    shm_size: 64gb
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --port 8899
