# image size
height: 224
width: 224

# augmentation inside dataset
transform:
  train:
    - name: CropMargin
      params:
        p: 1.0
    - name: Resize
      params:
        p: 1.0
        height: ${augmentation.height}
        width: ${augmentation.width}
    - name: HorizontalFlip
      params:
        p: 0.5
    - name: ToGray
      params:
        p: 1.0
    - name: Normalize
      params:
        p: 1.0
        mean: [0.5, 0.5, 0.5]
        std: [0.2, 0.2, 0.2]
    - name: KeepFirstChannel
      params:
        p: 1.0
  validation:
    - name: CropMargin
      params:
        p: 1.0
    - name: Resize
      params:
        p: 1.0
        height: ${augmentation.height}
        width: ${augmentation.width}
    - name: ToGray
      params:
        p: 1.0
    - name: Normalize
      params:
        p: 1.0
        mean: [0.5, 0.5, 0.5]
        std: [0.2, 0.2, 0.2]
    - name: KeepFirstChannel
      params:
        p: 1.0
  test:
    - name: CropMargin
      params:
        p: 1.0
    - name: Resize
      params:
        p: 1.0
        height: ${augmentation.height}
        width: ${augmentation.width}
    - name: ToGray
      params:
        p: 1.0
    - name: Normalize
      params:
        p: 1.0
        mean: [0.5, 0.5, 0.5]
        std: [0.2, 0.2, 0.2]
    - name: KeepFirstChannel
      params:
        p: 1.0

# augmenatation like mixup
strong_transform:
  # name: mixup
  # params:
  #   p: 1
  #   alpha: 0.5

# augmentation on torch.Tensor
batch_transform:
  source: "torchvision" # torchvision, kornia, torch_audiomentations
  train:

  validation:

  test:
#   - name: RandomHorizontalFlip
#     params:
#       p: 0.5

# TTA
# tta_transform:
#   _target_: ttach.ClassificationTTAWrapper
#   transforms:
#     _target_: ttach.aliases.hflip_transform
#   merge_mode: "mean"
